### ISSUE TITLE
Are parameters with no "infinite" dimensions allowed?

### ISSUE THREAD

**Issue by callumm-graphcore** [microsoft/mup#29]
Hi,

Is it valid to have parameters that have no "infinite" dimensions? [This line](https://github.com/microsoft/mup/blob/main/mup/init.py#L128) suggests that it is, but I can't find anything in the paper that explains how this case should be dealt with.

With thanks,
Callum

**Comment by edwardjhu** [comment]
Hi Callum,

Yes, it's possible to have parameters with only finite dimensions. For example, given a finite output dimension d_out, the bias vector for the last layer will have dimension 1 x d_out.

**Comment by callumm-graphcore** [comment]
Thanks Edward! Is there a part of the paper that explains what the correct scaling is in this case? Would this apply even if you had a linear layer where neither the input nor the output dimension was scaled?

**Comment by edwardjhu** [comment]
The bias example I gave is covered under `input weights & biases` in Table 3, 8, and 9, and it has a constant init and LR.

Yes, it also applies when you have a linear layer. We might not have talked about it specifically in the paper since it's less common, but you should use a constant init and LR.

**Comment by callumm-graphcore** [comment]
Ah, OK, I see now. Thank you very much!

**Comment by thegregyang** [comment]
Yes that is allowed.
